### ISSUE TITLE
Feature Idea: Link Note md to png

### ISSUE THREAD

**Issue by Zevoros-cyber** [philips/obsidian-plugin-supernote#6]
Brandon, it would be most helpful in terms of workflow to link the md to the png, so that the png is displayed right after the text.  For example:

![image](https://github.com/philips/obsidian-plugin-supernote/assets/29148183/41075f51-925a-4422-9a13-45827640c34f)

**Comment by philips** [comment]
Great idea. One thing I wonder is should I interleave the images of each page with the text or have a separate text then images section. 

I am sure I can add a template down the line but need to decide on the v1 default

**Comment by Zevoros-cyber** [comment]
I'd prefer to keep it separate, although that can be an option on the plugin.  On a related note, it also should be an option to consolidate multi-page notes into a single md.  For this, the image for the page would also appear after the page's text.

**Comment by philips** [comment]
Ah ok so you want one note per page?

**Comment by Zevoros-cyber** [comment]
Not quite sure we are saying same thing. Right now, the plug-in will take a
multipage note and break it up into separate md files. It would be
preferable, as an option, to keep it combined as a single md. A command
option could, on demand, break it up into separate md's.

By losing the flow between pages of the note, the thought flow can be lost.

It would be very useful if the SN headings could be respected in the note
with MD heading and subheading markers.  This will make more sense when you
get a device.

**Comment by philips** [comment]
I think this is fixed in v2.0.0 just released.
